CREATE TABLE IF NOT EXISTS `managebac_connections` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `encrypted_feed_url` TEXT NOT NULL,
    `feed_host` VARCHAR(255) NOT NULL,
    `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `enabled` BOOLEAN NOT NULL DEFAULT TRUE,
    `sync_interval_minutes` INT NOT NULL DEFAULT 10,
    `etag` VARCHAR(512) NULL,
    `last_modified` VARCHAR(255) NULL,
    `next_sync_at` DATETIME NULL,
    `last_sync_started_at` DATETIME NULL,
    `last_success_at` DATETIME NULL,
    `consecutive_failures` INT NOT NULL DEFAULT 0,
    `last_error_code` VARCHAR(80) NULL,
    `last_error_detail` VARCHAR(500) NULL,
    `lease_owner` VARCHAR(128) NULL,
    `lease_expires_at` DATETIME NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_managebac_connection_user` (`user_id`),
    KEY `ix_managebac_connection_due` (`enabled`, `next_sync_at`),
    KEY `ix_managebac_connection_lease` (`lease_expires_at`),
    CONSTRAINT `fk_managebac_connection_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `managebac_task_links` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `connection_id` INT NOT NULL,
    `external_uid` VARCHAR(512) NOT NULL,
    `task_id` INT NOT NULL,
    `remote_hash` VARCHAR(64) NOT NULL,
    `remote_sequence` INT NULL,
    `remote_last_modified` DATETIME NULL,
    `remote_snapshot` JSON NOT NULL,
    `source_url` TEXT NULL,
    `remote_state` VARCHAR(20) NOT NULL DEFAULT 'active',
    `first_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `last_seen_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `missing_count` INT NOT NULL DEFAULT 0,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_managebac_connection_uid` (`connection_id`, `external_uid`),
    UNIQUE KEY `uq_managebac_link_task` (`task_id`),
    KEY `ix_managebac_link_connection_seen` (`connection_id`, `last_seen_at`),
    CONSTRAINT `fk_managebac_link_connection` FOREIGN KEY (`connection_id`) REFERENCES `managebac_connections` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_managebac_link_task` FOREIGN KEY (`task_id`) REFERENCES `task` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `managebac_sync_runs` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `connection_id` INT NOT NULL,
    `trigger` VARCHAR(20) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'running',
    `http_status` INT NULL,
    `total_items` INT NOT NULL DEFAULT 0,
    `added_count` INT NOT NULL DEFAULT 0,
    `updated_count` INT NOT NULL DEFAULT 0,
    `unchanged_count` INT NOT NULL DEFAULT 0,
    `cancelled_count` INT NOT NULL DEFAULT 0,
    `skipped_count` INT NOT NULL DEFAULT 0,
    `error_code` VARCHAR(80) NULL,
    `error_detail` VARCHAR(500) NULL,
    `started_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `finished_at` DATETIME NULL,
    PRIMARY KEY (`id`),
    KEY `ix_managebac_run_connection_started` (`connection_id`, `started_at`),
    CONSTRAINT `fk_managebac_run_connection` FOREIGN KEY (`connection_id`) REFERENCES `managebac_connections` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
