-- Additive long-term scheduling memory and personalization schema.
-- Safe for the current application schema: no existing task, deadline, plan,
-- reminder, role-card, or audit row is rewritten or deleted.

CREATE TABLE IF NOT EXISTS `scheduling_consent_settings` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `operational_personalization_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `work_session_capture_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `llm_memory_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `cross_user_learning_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `near_tie_exploration_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `raw_event_retention_days` INT NOT NULL DEFAULT 365,
    `rebuild_after_reset_enabled` BOOLEAN NOT NULL DEFAULT FALSE,
    `policy_version` VARCHAR(64) NOT NULL,
    `version` INT NOT NULL DEFAULT 1,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `accepted_at` TIMESTAMP NULL,
    `withdrawn_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_scheduling_consent_user` (`user_id`),
    KEY `ix_sched_consent_user_version` (`user_id`, `version`),
    CONSTRAINT `ck_sched_consent_retention_days` CHECK (`raw_event_retention_days` BETWEEN 30 AND 3650),
    CONSTRAINT `ck_sched_consent_version` CHECK (`version` >= 1),
    CONSTRAINT `fk_sched_consent_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_consent_revisions` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `version` INT NOT NULL,
    `policy_version` VARCHAR(64) NOT NULL,
    `settings_snapshot` JSON NOT NULL,
    `change_source` VARCHAR(32) NOT NULL DEFAULT 'user',
    `changed_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_consent_revision` (`user_id`, `version`),
    KEY `ix_sched_consent_revision_time` (`user_id`, `changed_at`, `id`),
    CONSTRAINT `fk_sched_consent_revision_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_decision_events` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `decision_point_id` VARCHAR(36) NOT NULL,
    `user_id` INT NOT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `source_id` INT NOT NULL,
    `correlation_id` VARCHAR(64) NULL,
    `idempotency_key` VARCHAR(128) NULL,
    `occurred_at` TIMESTAMP NOT NULL,
    `local_date` DATE NOT NULL,
    `timezone` VARCHAR(64) NOT NULL,
    `event_schema_version` VARCHAR(64) NOT NULL,
    `context_hash` VARCHAR(64) NOT NULL,
    `context_snapshot` JSON NOT NULL,
    `candidate_snapshot` JSON NOT NULL,
    `displayed_candidate_ids` JSON NOT NULL,
    `selected_candidate_id` VARCHAR(128) NULL,
    `selection_source` VARCHAR(32) NOT NULL DEFAULT 'unknown',
    `automation_mode` VARCHAR(32) NOT NULL DEFAULT 'manual',
    `action_propensity` DECIMAL(8,7) NULL,
    `policy_version` VARCHAR(64) NOT NULL,
    `model_version` VARCHAR(64) NULL,
    `consent_version` INT NULL,
    `eligible_personal` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligible_cross_user` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `retention_expires_at` TIMESTAMP NULL,
    `invalidated_at` TIMESTAMP NULL,
    `outcome_link_status` VARCHAR(32) NOT NULL DEFAULT 'pending',
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_decision_point` (`decision_point_id`),
    UNIQUE KEY `uq_sched_decision_idempotency` (`user_id`, `idempotency_key`),
    KEY `ix_sched_decision_user_time` (`user_id`, `occurred_at`, `id`),
    KEY `ix_sched_decision_source` (`user_id`, `source_type`, `source_id`),
    KEY `ix_sched_decision_retention` (`retention_expires_at`, `invalidated_at`),
    CONSTRAINT `ck_sched_decision_propensity` CHECK (`action_propensity` IS NULL OR (`action_propensity` > 0 AND `action_propensity` <= 1)),
    CONSTRAINT `fk_sched_decision_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_work_sessions` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `public_id` VARCHAR(36) NOT NULL,
    `user_id` INT NOT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `source_id` INT NOT NULL,
    `active_key` VARCHAR(128) NULL,
    `state` VARCHAR(20) NOT NULL DEFAULT 'active',
    `timezone` VARCHAR(64) NOT NULL,
    `started_at` TIMESTAMP NOT NULL,
    `current_interval_started_at` TIMESTAMP NULL,
    `paused_at` TIMESTAMP NULL,
    `ended_at` TIMESTAMP NULL,
    `accumulated_active_seconds` INT NOT NULL DEFAULT 0,
    `last_event_id` VARCHAR(36) NULL,
    `version` INT NOT NULL DEFAULT 1,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_work_session_public` (`public_id`),
    UNIQUE KEY `uq_sched_work_session_active` (`active_key`),
    KEY `ix_sched_work_session_user_state` (`user_id`, `state`, `updated_at`),
    KEY `ix_sched_work_session_source` (`user_id`, `source_type`, `source_id`),
    CONSTRAINT `ck_sched_work_session_state` CHECK (`state` IN ('active','paused','stopped','discarded')),
    CONSTRAINT `ck_sched_work_session_seconds` CHECK (`accumulated_active_seconds` >= 0),
    CONSTRAINT `fk_sched_work_session_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_work_events` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `event_id` VARCHAR(36) NOT NULL,
    `user_id` INT NOT NULL,
    `session_id` INT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `source_id` INT NOT NULL,
    `event_type` VARCHAR(32) NOT NULL,
    `idempotency_key` VARCHAR(128) NOT NULL,
    `occurred_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `effective_at` TIMESTAMP NOT NULL,
    `effective_local_date` DATE NOT NULL,
    `timezone` VARCHAR(64) NOT NULL,
    `before_values` JSON NOT NULL,
    `after_values` JSON NOT NULL,
    `provenance` VARCHAR(32) NOT NULL,
    `confidence` VARCHAR(16) NOT NULL,
    `correction_of_event_id` VARCHAR(36) NULL,
    `decision_point_id` VARCHAR(36) NULL,
    `plan_id` INT NULL,
    `consent_version` INT NULL,
    `event_schema_version` VARCHAR(64) NOT NULL,
    `eligible_personal` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligible_cross_user` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `retention_expires_at` TIMESTAMP NULL,
    `invalidated_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_work_event_public` (`event_id`),
    UNIQUE KEY `uq_sched_work_event_idempotency` (`user_id`, `idempotency_key`),
    KEY `ix_sched_work_event_user_time` (`user_id`, `effective_at`, `id`),
    KEY `ix_sched_work_event_source` (`user_id`, `source_type`, `source_id`, `effective_at`),
    KEY `ix_sched_work_event_session` (`session_id`, `id`),
    KEY `ix_sched_work_event_retention` (`retention_expires_at`, `invalidated_at`),
    CONSTRAINT `fk_sched_work_event_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sched_work_event_session` FOREIGN KEY (`session_id`) REFERENCES `scheduling_work_sessions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_outcome_labels` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `source_type` VARCHAR(32) NOT NULL,
    `source_id` INT NOT NULL,
    `decision_point_id` VARCHAR(36) NULL,
    `episode` INT NOT NULL DEFAULT 1,
    `derivation_version` VARCHAR(64) NOT NULL,
    `outcome_cutoff_at` TIMESTAMP NOT NULL,
    `active_minutes` DECIMAL(10,2) NULL,
    `active_minutes_provenance` VARCHAR(32) NULL,
    `interval_complete` BOOLEAN NOT NULL DEFAULT FALSE,
    `start_latency_minutes` DECIMAL(10,2) NULL,
    `planned_actual_ratio` DECIMAL(10,4) NULL,
    `progress_ratio` DECIMAL(6,5) NULL,
    `completed_before_personal_target` BOOLEAN NULL,
    `completed_before_hard_deadline` BOOLEAN NULL,
    `terminal_state` VARCHAR(32) NOT NULL DEFAULT 'unknown',
    `is_censored` BOOLEAN NOT NULL DEFAULT TRUE,
    `censoring_reason` VARCHAR(32) NULL,
    `censored_at` TIMESTAMP NULL,
    `label_confidence` VARCHAR(16) NOT NULL DEFAULT 'unknown',
    `eligible_personal` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligible_evaluation` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligible_cross_user` BOOLEAN NOT NULL DEFAULT FALSE,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `invalidated_at` TIMESTAMP NULL,
    `derived_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_outcome_derivation` (`user_id`, `source_type`, `source_id`, `episode`, `derivation_version`, `outcome_cutoff_at`),
    KEY `ix_sched_outcome_user_source` (`user_id`, `source_type`, `source_id`, `episode`),
    KEY `ix_sched_outcome_eligibility` (`user_id`, `eligible_personal`, `invalidated_at`),
    CONSTRAINT `ck_sched_outcome_progress` CHECK (`progress_ratio` IS NULL OR (`progress_ratio` >= 0 AND `progress_ratio` <= 1)),
    CONSTRAINT `fk_sched_outcome_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_memory_entries` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `memory_id` VARCHAR(36) NOT NULL,
    `user_id` INT NOT NULL,
    `tier` VARCHAR(32) NOT NULL,
    `memory_key` VARCHAR(100) NOT NULL,
    `value_json` JSON NOT NULL,
    `display_text` TEXT NOT NULL,
    `source` VARCHAR(32) NOT NULL,
    `evidence_event_ids` JSON NOT NULL,
    `evidence_hash` VARCHAR(64) NULL,
    `evidence_count` INT NOT NULL DEFAULT 0,
    `confidence` DECIMAL(6,5) NULL,
    `maturity` DECIMAL(6,5) NULL,
    `valid_from` DATE NULL,
    `valid_until` DATE NULL,
    `expires_at` TIMESTAMP NULL,
    `supersedes_memory_id` VARCHAR(36) NULL,
    `superseded_by_memory_id` VARCHAR(36) NULL,
    `contradiction_state` VARCHAR(32) NOT NULL DEFAULT 'none',
    `generated_by_model` VARCHAR(128) NULL,
    `prompt_version` VARCHAR(64) NULL,
    `schema_version` VARCHAR(64) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'current',
    `suppression_fingerprint` VARCHAR(64) NULL,
    `consent_version` INT NULL,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `last_retrieved_at` TIMESTAMP NULL,
    `last_used_purpose` VARCHAR(32) NULL,
    `invalidated_at` TIMESTAMP NULL,
    `deleted_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_memory_public` (`memory_id`),
    KEY `ix_sched_memory_user_status` (`user_id`, `status`, `tier`, `updated_at`),
    KEY `ix_sched_memory_user_key` (`user_id`, `memory_key`, `valid_until`),
    KEY `ix_sched_memory_evidence_hash` (`user_id`, `evidence_hash`, `status`),
    KEY `ix_sched_memory_suppression` (`user_id`, `suppression_fingerprint`, `status`),
    CONSTRAINT `fk_sched_memory_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_feature_snapshots` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `user_id` INT NOT NULL,
    `scope_type` VARCHAR(32) NOT NULL,
    `scope_key` VARCHAR(191) NOT NULL,
    `reference_date` DATE NOT NULL,
    `window_start` DATE NULL,
    `window_end` DATE NULL,
    `feature_schema_version` VARCHAR(64) NOT NULL,
    `source_eligibility_watermark` INT NOT NULL,
    `effective_sample_size` DECIMAL(12,4) NOT NULL DEFAULT 0,
    `sufficient_statistics` JSON NOT NULL,
    `recent_statistics` JSON NOT NULL,
    `recency_policy` JSON NOT NULL,
    `drift_state` VARCHAR(20) NOT NULL DEFAULT 'stable',
    `eligible_cross_user` BOOLEAN NOT NULL DEFAULT FALSE,
    `invalidated_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_feature_snapshot` (`user_id`, `scope_type`, `scope_key`, `reference_date`, `feature_schema_version`),
    KEY `ix_sched_feature_user_reference` (`user_id`, `reference_date`, `id`),
    KEY `ix_sched_feature_scope` (`scope_type`, `scope_key`, `reference_date`),
    CONSTRAINT `fk_sched_feature_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_model_registry` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `model_id` VARCHAR(36) NOT NULL,
    `user_id` INT NULL,
    `model_type` VARCHAR(32) NOT NULL,
    `scope` VARCHAR(32) NOT NULL,
    `lifecycle` VARCHAR(20) NOT NULL DEFAULT 'candidate',
    `algorithm_version` VARCHAR(64) NOT NULL,
    `feature_schema_version` VARCHAR(64) NOT NULL,
    `label_version` VARCHAR(64) NULL,
    `calibration_version` VARCHAR(64) NULL,
    `source_eligibility_watermark` INT NOT NULL DEFAULT 1,
    `training_window_start` TIMESTAMP NULL,
    `training_window_end` TIMESTAMP NULL,
    `effective_sample_size` DECIMAL(12,4) NOT NULL DEFAULT 0,
    `artifact_json` JSON NOT NULL,
    `evaluation_metrics` JSON NOT NULL,
    `slice_metrics` JSON NOT NULL,
    `fallback_model_id` INT NULL,
    `serving_started_at` TIMESTAMP NULL,
    `serving_ended_at` TIMESTAMP NULL,
    `lifecycle_reason` VARCHAR(255) NULL,
    `approved_by` VARCHAR(64) NULL,
    `invalidated_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_model_public` (`model_id`),
    KEY `ix_sched_model_serving` (`user_id`, `model_type`, `lifecycle`, `created_at`),
    KEY `ix_sched_model_scope` (`scope`, `model_type`, `created_at`),
    CONSTRAINT `ck_sched_model_lifecycle` CHECK (`lifecycle` IN ('candidate','shadow','promoted','superseded','killed','invalidated')),
    CONSTRAINT `fk_sched_model_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sched_model_fallback` FOREIGN KEY (`fallback_model_id`) REFERENCES `scheduling_model_registry` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_model_predictions` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `prediction_id` VARCHAR(36) NOT NULL,
    `user_id` INT NOT NULL,
    `decision_point_id` VARCHAR(36) NULL,
    `model_registry_id` INT NULL,
    `context_hash` VARCHAR(64) NOT NULL,
    `prediction_type` VARCHAR(32) NOT NULL,
    `horizon_date` DATE NULL,
    `p10` DECIMAL(12,4) NULL,
    `p50` DECIMAL(12,4) NULL,
    `p90` DECIMAL(12,4) NULL,
    `probability` DECIMAL(8,7) NULL,
    `evidence_maturity` DECIMAL(6,5) NOT NULL DEFAULT 0,
    `calibration_state` VARCHAR(20) NOT NULL DEFAULT 'unknown',
    `feature_contributions` JSON NOT NULL,
    `baseline_rank` INT NULL,
    `learned_rank` INT NULL,
    `learned_adjustment` DECIMAL(12,6) NOT NULL DEFAULT 0,
    `serving_mode` VARCHAR(20) NOT NULL,
    `latency_ms` INT NOT NULL DEFAULT 0,
    `consent_version` INT NULL,
    `eligibility_watermark` INT NOT NULL DEFAULT 1,
    `invalidated_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_prediction_public` (`prediction_id`),
    KEY `ix_sched_prediction_user_time` (`user_id`, `created_at`, `id`),
    KEY `ix_sched_prediction_decision` (`decision_point_id`, `prediction_type`),
    CONSTRAINT `ck_sched_prediction_probability` CHECK (`probability` IS NULL OR (`probability` >= 0 AND `probability` <= 1)),
    CONSTRAINT `fk_sched_prediction_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE,
    CONSTRAINT `fk_sched_prediction_model` FOREIGN KEY (`model_registry_id`) REFERENCES `scheduling_model_registry` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `scheduling_governance_jobs` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `job_id` VARCHAR(36) NOT NULL,
    `idempotency_key` VARCHAR(191) NOT NULL,
    `user_id` INT NULL,
    `job_type` VARCHAR(32) NOT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'pending',
    `payload_json` JSON NOT NULL,
    `attempts` INT NOT NULL DEFAULT 0,
    `not_before` TIMESTAMP NULL,
    `lease_owner` VARCHAR(128) NULL,
    `lease_expires_at` TIMESTAMP NULL,
    `last_error_code` VARCHAR(64) NULL,
    `last_error_detail` VARCHAR(500) NULL,
    `completed_at` TIMESTAMP NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_sched_governance_job_public` (`job_id`),
    UNIQUE KEY `uq_sched_governance_job_idempotency` (`idempotency_key`),
    KEY `ix_sched_governance_job_claim` (`status`, `not_before`, `lease_expires_at`, `id`),
    KEY `ix_sched_governance_job_user` (`user_id`, `job_type`, `created_at`),
    CONSTRAINT `ck_sched_governance_job_status` CHECK (`status` IN ('pending','leased','succeeded','failed','cancelled')),
    CONSTRAINT `ck_sched_governance_job_attempts` CHECK (`attempts` >= 0),
    CONSTRAINT `fk_sched_governance_job_user` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
